### ISSUE TITLE
can /opt/nidas/ARCHLIBDIR be just /opt/nidas/lib?

### ISSUE THREAD

**Issue by garyjg** [ncareol/nidas#8]
I am thinking that ARCHLIBDIR is left over from when the nidas install tree (/opt/nidas) tried to accommodate multiple architectures in the same tree, like x86_64, armbe, and armel.  At this point, though, I think the /opt/nidas tree is only ever one architecture, and as far as I can tell, there is no benefit to making the library directory name architecture-specific.  So rather than these:
- `/opt/nidas/lib64`
- `/opt/nidas/lib/i386-linux-gnu/`
- `/opt/nidas/lib/arm-linux-gnueabihf`
the libraries would always go into just `/opt/nidas/lib`.  On Debian, I assume the `ld.so.conf.d file` would still have to have the architecture embedded in it (`nidas-i386-linux-gnu.conf`), but I don't think there's a reason the library path in that file has to have the architecture in the path name.

If we ever needed to install nidas for two different architectures on a system, then I guess we could just make the entire prefix architecture-specific, like /opt/nidas-i386 or /opt/nidas-armbe.

This would simplify lots of scripts and build configuration which have to figure out and apply the right `ARCHLIBDIR`.  It would also allow removing the selinux dependencies from the nidas RPMs, because files under `/opt/nidas/lib` would automatically have the right context on systems where selinux is installed.  There would be no need to install a custom context for `/opt/nidas/lib64`.

So what am I missing?  Would using `/opt/nidas/lib` for all systems break anything?

**Comment by topher800** [comment]
To make sure I am wrong at least once this week, I am going to state empathetically that you are missing nothing and that /opt/nidas/lib for all architectures will break nothing.

The existing structure dates back to when cross-compiling happened on the aircraft server, so all architectures had to be supported, and then the dsms scp'ed the necessary files at boot time.  But the /opt/nidas-i386/ organization might have been cleaner.
